### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by xKamekazi** [agiveygives/eso-craft-request#108]
### Required
1. What is your guild's name? Veterans Gaming

2. What discord webhook would you like the requests to send to? [REDACTED]

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.  @Crafter

### Optional
5. What image would you like displayed on your guild branding in the footer? Ebonheart Pact Dragon

6. Would you like you branding to link to your guild website? If yes, what is the url?

7. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com). Black and Red

9. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)

**Comment by xKamekazi** [comment]
Correct role id 
1124014132811812935

**Comment by agiveygives** [comment]
Just wanted to pop in to say I've seen this, and will get it set up as soon as I'm back at my computer on Tuesday 🤌

**Comment by xKamekazi** [comment]
Thanks for the reply. And take your time! I'm on a short vacation myself. I
was so confused setting up a Discord server for the first time. So if I
messed anything up; let me know!

**Comment by agiveygives** [comment]
Sorry for the wait! It should be all setup, and thank you so much for getting the correct role id!

https://veteransgaming.esocraftrequest.com/

**Comment by xKamekazi** [comment]
Thanks you! Yeah; I had to learn a bit aboot how Discord works in the background. But I've seen the test and did my own and it's working! Thank you so much. This will make craft requests soooo much easier.
