### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by hightechstl** [agiveygives/eso-craft-request#26]
### Required
1. What is your guild's name?
Oni Knights

2. What discord webhook would you like the requests to send to?
https://discordapp.com/api/webhooks/740324291110895756/xfruRaRfDfqNpXqaOIAwYapjR9A0YSUIJHJiiFNbbOCQaThKk5Cn4rY9havNUkPIrtTH

3. What Discord role would you like the request to tag? You can get the role id by typing `\@roleName` into your discord server.
@Master Crafter

### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
onicrafts.esocraftrequest.com

**Comment by agiveygives** [comment]
@hightechstl I need the role ID from discord. It should be a long number.

> You can get the role id by typing `\@roleName` into your discord server.

**Comment by hightechstl** [comment]
> @hightechstl I need the role ID from discord. It should be a long number.
> 
> > You can get the role id by typing `\@roleName` into your discord server.

740325117812539422

Sorry about that

**Comment by agiveygives** [comment]
It's all set up. https://oniknights.esocraftrequest.com/

If you want a picture down where the placeholder is, just post it on here.

Thanks :)
