### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Nervani** [agiveygives/eso-craft-request#40]
### Required
1. What is your guild's name?
Crazy Elves

2. What discord webhook would you like the requests to send to?
https://discordapp.com/api/webhooks/748185448022802553/1y0x079yboi79Ly6ipx9BwYua2H5BPmbHrlkV_Qvpgf23kJeUwCiuLeXyUDzo3Qz5wEV

3. What Discord role would you like the request to tag? You can get the role id by typing `\@roleName` into your discord server.
@Crafter (<@&747178846045863946>)

### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)

**Comment by agiveygives** [comment]
https://crazyelves.esocraftrequest.com/

If you want to get your discord image to display on the footer where the placeholder is, make another issue and just paste the image in there. If you need help pulling the image from discord, feel free to ask here https://discord.gg/uEyzbrE
