### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by FriGiN** [agiveygives/eso-craft-request#50]
### Required
1. What is your guild's name?
FriGiN Goons

2. What discord webhook would you like the requests to send to?
https://discordapp.com/api/webhooks/754761457345888307/f4K6AH0OQEjflyD4fVmf2tJTbsGM0ihThaCX9dHN90hS6gS6q_6D_lOAiI3FeXe4S5-x

3. What Discord role would you like the request to tag? You can get the role id by typing `\@roleName` into your discord server.
@Crafters

### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?
https://www.frigingoon.com/

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).
something close to #50f87030

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
frigingoons.esocraftingrequest.com

**Comment by agiveygives** [comment]
@FriGiN - please answer the questions on the template so I can onboard your guild

**Comment by FriGiN** [comment]
> @FriGiN - please answer the questions on the template so I can onboard your guild

yeah i derped i had this window open twice closed the one that i put the info in and submitted the one i had blank.. sorry!

**Comment by agiveygives** [comment]
For the role, I need the ID. There are instructions on the template for how to get the role ID. It should be a string of numbers.

**Comment by FriGiN** [comment]
754760878108311552

**Comment by agiveygives** [comment]
Thanks! I'm away from my computer right now, but I'll get you all set up as soon as I can tonight.

**Comment by FriGiN** [comment]
no rush in any means of the word... happy you do all this its great, and thanks for adding my suggestion a lot of my guildies that use the service in one of my guild love it!

**Comment by agiveygives** [comment]
No Problem, it was a really good idea!

Your all ready to go with https://frigingoons.esocraftrequest.com/

The header color is exactly what you wanted. Since it had a low opacity, it mixed with the black background and made darker green since . If you want to change the color or add an image at the bottom where the placeholder is, just open a new issue or reach out on the discord server.
