### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Nervani** [agiveygives/eso-craft-request#52]
### Required
1. What is your guild's name?
Crazy Elves
2. What discord webhook would you like the requests to send to?
https://discordapp.com/api/webhooks/766305127375831060/K0TAfCMk58dLuLgDvQOZLNj1pWVwtMsdWk2HTYrJHukEQn-JsJK2oqTRz2UCuIO73zD0
3. What Discord role would you like the request to tag? You can get the role id by typing `\@roleName` into your discord server.
@Crafter
### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)

8. Comment
We had a accident on our server the other day where everything got wiped.
Would love to get this up and running again :)

**Comment by agiveygives** [comment]
@Nervani I'm gonna need the role ID. Instructions on how to get that are in the issue template.

**Comment by Nervani** [comment]
Ah sorry mate, just got home from work and are tired xD

ID: 747178846045863946
