### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by CasaCercone** [agiveygives/eso-craft-request#55]
### Required
1. What is your guild's name?
Casa Cercone
2. What discord webhook would you like the requests to send to?
https://discord.com/api/webhooks/777655020937674802/rRC3IO3YTbcj-8j_rktXNbM65w4zQIkeRtzrENY6msyzupDYMReNPrvPRFUddf06Qa8S
3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.
<@&777653105314496522>
### Optional
4. What image would you like displayed on your guild branding in the footer?
I tried attaching the Picture but i don't see it attached... not sure if it was successful 
5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).
Colors from the picture please
7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
CasaCercone.esocraftrequest.com

**Comment by agiveygives** [comment]
@CasaCercone I'm not seeing the picture, if you just copy paste the image into the textbox, it should show up. If you're still having issues doing it on github, you can message me on discord JukesMcGee#4228

**Comment by agiveygives** [comment]
https://casacercone.esocraftrequest.com/

If you want to change the colors, or need to update anything in the future. Open a ticket or reach out on Discord. Thank you!
