### ISSUE TITLE
1. Friendsintamriel, [ONBOARDING]

### ISSUE THREAD

**Issue by foddah66** [agiveygives/eso-craft-request#56]
### Required
1. Friendsintamriel

2. https://discordapp.com/api/webhooks/778122100996440065/1iM5Y4XuXgrSNOLI5XTUqO1Hl1EEG28DMDl7zCVYNYr-XVIvxvT_7PmwI5-_t-Bj_fWQ

3. @crafter
### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)

**Comment by agiveygives** [comment]
@foddah66 I need the role ID for your crafter tag. 

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.

**Comment by agiveygives** [comment]
Closing since I have not gotten a response in almost a year.
