### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by deadohiosky48** [agiveygives/eso-craft-request#57]
### Required
1. What is your guild's name? JOOB NATION

2. What discord webhook would you like the requests to send to? https://discord.com/api/webhooks/782212666948190239/dKgkjka5S7m2F6VALur0ZxX1Tvv11MOvEFQXpcNgqtdwt89jbaW4Tch09_bx-y83cDSJ

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server. <@&781877392481452042>

### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com) joobnation.esocraftrequest.com

**Comment by agiveygives** [comment]
https://joobnation.esocraftrequest.com/

If you want to add an image or change the colors, please open another ticket, or message me on Discord.
https://discord.gg/3SFgtcA
JukesMcGee#4228

**Comment by deadohiosky48** [comment]
Works great, thank you so much!
