### ISSUE TITLE
French Version 

### ISSUE THREAD

**Issue by emiliesecherre** [agiveygives/eso-craft-request#58]
**Is your feature request related to a current project? If so, which project?**
No

**Describe the solution you'd like**
Build a french version of this tool

**Additional context**
French community is very present on this game, but most of them doesn't speak English enough to use your web tool easily. So, if this idea interests you, i can translate the whole tool. You would then be able to give both english or French version to eso guilds. Finally, i'm a dev, so if its more suitable for you i can translate this tool directly on its code.

**Comment by agiveygives** [comment]
I'm very interested. It's been on my list to add in18n to the project, but the need hasn't really come up. So, it keeps getting pushed back. I'd love to work with you on this if you'd want to!

Feel free to reach out on discord JukesMcGee#4228

**Comment by agiveygives** [comment]
I started work in https://github.com/agiveygives/eso-craft-request/tree/i18n-french

**Comment by emiliesecherre** [comment]
I'm starting working on it, but an issue occured : when running "npm install" i'm getting errors like this one : "npm WARN tar EPERM: operation not permitted, open 'C:\Users\Thanael\Desktop\eso-craft-request-i18n-french\node_modules\.staging\performance-now-179c63b2\license.txt'". How could i fix them ?
