### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Lazurick** [agiveygives/eso-craft-request#72]
### Required
1. What is your guild's name?
Group Z

2. What discord webhook would you like the requests to send to?
https://discord.com/api/webhooks/812702674721964052/SPKiw6Eu7ymFPE1IZ5ePzFDlhbCHjRPlzwKsYIEUmiQ_woDnzL__85QREx3ZbVL7QQLC

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.
<@&812702982873415722>

### Optional
4. What image would you like displayed on your guild branding in the footer?
https://en.uesp.net/wiki/File:ON-Icon-Transparent_Logo.png

5. Would you like you branding to link to your guild website? If yes, what is the url?
No

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).
Default Colors

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
groupz.esocraftrequest.com

**Comment by agiveygives** [comment]
https://groupz.esocraftrequest.com/

Thank you for your request! please open a ticket or reach out on [Discord](https://discord.gg/3SFgtcA) for any additional questions or requests.
