### ISSUE TITLE
Shield Traits Incorrect

### ISSUE THREAD

**Issue by Lazurick** [agiveygives/eso-craft-request#73]
**Describe the bug**
When selecting traits for a shield the weapon traits show up. Shield traits are based on the same traits as armor.

**To Reproduce**
Select Primary or Secondary Weapon.
Select Shield
Select Traits. (Incorrect traits shown)

**Expected behavior**
Traits for shield should be the same as armor traits.

**Comment by agiveygives** [comment]
Thanks for logging this. It should be fixed now!
