### ISSUE TITLE
Update GroupZ Webhook from Discord to Guilded

### ISSUE THREAD

**Issue by Lazurick** [agiveygives/eso-craft-request#79]
Change GroupZ Webhook.
Site: https://groupz.esocraftrequest.com/

Current Webhook: https://discord.com/api/webhooks/812702674721964052/SPKiw6Eu7ymFPE1IZ5ePzFDlhbCHjRPlzwKsYIEUmiQ_woDnzL__85QREx3ZbVL7QQLC

New Webhook: 
https://media.guilded.gg/webhooks/190dc983-d41f-4179-b41a-b4a132f78a87/6Y58ar0fde6o2gMgASU0KwuSceYicKmSK6awEcUkYYIee0MKukYKMQcaaSQWACkokY0gUo4yCUMakOyQqECQ2Y

Note: Happy Father's Day :)

**Comment by agiveygives** [comment]
Do you have a tag in guilded you want me to use?

I assume I'll still need the tag id for guilded, but I'm not sure how to go about getting that within their app.

**Comment by agiveygives** [comment]
@Lazurick I updated the webhook. I'll leave this open just in case I need to make more changes with regards to the tags.

**Comment by Lazurick** [comment]
@agiveygives it works.

What do you mean by tag?

![image](https://user-images.githubusercontent.com/62221251/122797332-fe5dac80-d284-11eb-84e0-4e79edb87a1f.png)

**Comment by agiveygives** [comment]
That <@&8127029828733415722> translates to a @ tag in discord.

It also seems like Guilded doesn't like some of the formatting characters :/ 

If it doesn't bother you that much, I can just leave it until I have time to look more into the guilded webhooks, but, if it's a big deal, I can set aside some time this week to get it figured out.

**Comment by agiveygives** [comment]
@Lazurick I logged https://github.com/agiveygives/eso-craft-request/issues/80

If there are any other weird things you notice while using it, comment on that.

**Comment by Lazurick** [comment]
It is no bother at all, just when you get time to look into it. Below is the link to the Webhook API for Guilded, maybe it will help.

[Guilded Webhook API](https://guildedapi.com/resources/webhook/)

I will let you know if other issues come up.

**Comment by Lazurick** [comment]
Ah so that tag in Discord is calling out the Webhook. It seems in Discord when a Webhook is created that it also creates a role for it. Guilded does not create a role for their webhooks, so that tag is no needed I believe.
