### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Trelloak** [agiveygives/eso-craft-request#81]
### Required
1. What is your guild's name?
Riding the Drama Llama
2. What discord webhook would you like the requests to send to?
https://discordapp.com/api/webhooks/884206228153184267/8jAjjks7s_MxiSyDCZ38w-XuH0kyTnHnSdvZZglHKHWqDCGpVs_BKQE-XAFLAgLQV8cV
3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.
@Crafters
### Optional
4. What image would you like displayed on your guild branding in the footer?
https://memegenerator.net/instance/67108865/pancakes-llama-this-looks-like-a-job-for-drama-llama
5. Would you like you branding to link to your guild website? If yes, what is the url?
N/A
6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
dramallama.esocraftrequest.com

**Comment by agiveygives** [comment]
https://dramallama.esocraftrequest.com/

Let me know if there are any issues or any configuration options change
