### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Mythic-Wolfess** [agiveygives/eso-craft-request#86]
### Required
1. What is your guild's name? Shadowwolves

2. What discord webhook would you like the requests to send to?
https://discord.com/api/webhooks/892750606865924136/YmzE_ZRb2Fj-BQG6cEQvkVSWblHns--kBQ5UmQkbo9HueKWPqOEqMle0iK3y_lv4d_j-
3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.. -> 
<@&892747134275829760>
### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)

**Comment by agiveygives** [comment]
https://shadowwolves.esocraftrequest.com/
