### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by Tybian0627** [agiveygives/eso-craft-request#90]
### Required
1. What is your guild's name? The Silent Order

2. What discord webhook would you like the requests to send to?
__REDACTED__

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server. <@&879290049206829056>

### Optional
4. What image would you like displayed on your guild branding in the footer?
Silent Order Crafting Requests
5. Would you like you branding to link to your guild website? If yes, what is the url? None

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).
Use your default
7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
Silentordercrafting.esocraftquest.com

**Comment by agiveygives** [comment]
https://silentordercrafting.esocraftrequest.com/

Let me know if you need anything else 🎃
