### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by xKingDustyx** [agiveygives/eso-craft-request#98]
### Required
1. What is your guild's name?
Legion Zero

2. What discord webhook would you like the requests to send to?
REDACTED

3. What is the ID for the role would you like the request to tag? (Example: `<@&123456789123456789>`) You can get the role id by typing `\@roleName` into your discord server.
<@&954373506051735582>

### Optional
4. What image would you like displayed on your guild branding in the footer?

5. Would you like you branding to link to your guild website? If yes, what is the url?

6. What colors would you like for the header and footer? If you provide an image for the branding, I can pick colors based off that. Otherwise, I will use the colors use in the [demo](https://demo.esocraftrequest.com).
![image](https://user-images.githubusercontent.com/101818256/159013574-aa15253e-e119-4402-afef-be18ef9f6186.png)
**Addition Notes:** If you could just base the colors around the blue-ish or if it's possible to have the header made a darkened version of the image.

7. What would you like for your subdomain? (ex. myawesomeguild.esocraftrequest.com)
legionzero.esocraftrequest.com

**Comment by agiveygives** [comment]
https://legionzero.esocraftrequest.com/
